[package]
name = "udpPing"
version = "0.1.0"
authors = ["name <aaa@aaaa.aaa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rand = "0.6.5"
time = "*"